# Site settings
name: keeds.random
title: keeds.random
email: ""
description: "Just a random collection about random stuff I stumble across that I find interesting."
baseurl: ""
url: "http://keeds.github.io"
username: keeds
twitteruser: apkeedle

# Build settings
markdown: kramdown
permalinks: pretty
